### ISSUE TITLE
scss

### ISSUE THREAD

**Issue by stratboy** [loadingio/css-spinner#1]
Hi, thank you for this library. How about scss sources alternatives? Stylus is not so popular.

**Comment by zbryikt** [comment]
actually I'm thinking about this too. But we are currently using stylus in our product so I think it might need some tools to maintain between scss and stylus if we are going to provide scss source too. will take some time to plan on this.

**Comment by olets** [comment]
CSS is valid .scss Sass so index.css will work in a scss context

**Comment by zbryikt** [comment]
have done survey yet it seems hard to have a easy solution for this, and per olets's comment, this should be able to be done by using index.css directly. decide to stick with stylus for now. :)
