### ISSUE TITLE
Copy the CSS, HTML code

### ISSUE THREAD

**Issue by nowshad-hasan** [loadingio/css-spinner#13]
For the first time, I visited [https://loading.io/css/](https://loading.io/css/) and found out that I have to manually select-copy the HTML, CSS code. But it would be a great user experience if I could click the CSS, HTML button on right side and it would be copied in my cursor. Here is the sample image below. 
<img width="642" alt="Screenshot 2021-09-08 at 7 03 14 PM" src="https://user-images.githubusercontent.com/12959212/132514679-e3767aaa-f179-4cbd-988e-832cff77e1d8.png">

I can do it and make a PR if you want.

**Comment by zbryikt** [comment]
hi! thanks for the suggestion. I think this is doable yet not in high priority - will add this when I have time. will keep this issue open for now. :)

**Comment by nowshad-hasan** [comment]
Hi @zbryikt, I'm pretty much new to frontend development, still learning and long way to go. I really like to contribute to open source projects. So, if you are interested, I want to do it and make a PR.

**Comment by zbryikt** [comment]
PR is definitely welcome however the demo page is not in this repo but in the private repo of loading.io's website so you can't actually contribute to it here.

Perhaps we can make a standalone demo page here with Github pages or maybe migrate the demo page here - yet if there is no other reasons excepting for accepting PR, I tend to keep it as what it is now. :)

**Comment by zbryikt** [comment]
we have added the copy functionality on the button [in the page](https://loading.io/css/) so will close this issue. :)
