### ISSUE TITLE
Unable to find vars.styl

### ISSUE THREAD

**Issue by tcd** [loadingio/css-spinner#14]
Tried to download and build with some changed sizes, but can't find `vars.styl`. 
The file linked in the readme (https://github.com/loadingio/css-spinner/blob/master/vars.styl) is no longer there.

**Comment by tcd** [comment]
Just found [issue #6](https://github.com/loadingio/css-spinner/issues/6) from last year.
Going to close this, but the readme should probably be updated or dev/v2 should be merged into master. 
Thanks for the awesome spinners btw.

**Comment by zbryikt** [comment]
hi, seems it got deleted when merging dev/v2 back to master. have made some updates so it should work properly now. :)
