### ISSUE TITLE
vars.styl not found in repository

### ISSUE THREAD

**Issue by slawkens** [loadingio/css-spinner#15]
Hello,

in the README you state that to build the code, you need modify the file: **vars.styl**.

But I can't find the file anywhere in the repo.

The link is redirecting here: https://github.com/loadingio/css-spinner/blob/master/vars.styl

Also there is error running **npm run build**
`Error: ENOENT: no such file or directory, open 'vars.styl'`

**Comment by twnaing** [comment]
https://github.com/loadingio/css-spinner/blob/088aefa790d015e9c7df664d426374952e65124a/web/src/styl/vars.styl

before loadingio fix the issue, you could create the file.

**Comment by zbryikt** [comment]
hi! `vars.styl` is added, along with some bugs fixing. released as  v2.0.1 ( https://github.com/loadingio/css-spinner/releases/tag/v2.0.1 )
