### ISSUE TITLE
Error: Could not find module 'color' in build.ls

### ISSUE THREAD

**Issue by csphilli** [loadingio/css-spinner#20]
I looked through the entire package and couldn't see a specific module of simply `color`. It was being referenced in the first line of the `build.ls` file which is 
`require! <[fs fs-extra path progress color stylus pug uglifycss]>`

I changed `color` to `ldcolor` and that seemed to fix it.

This is my output after running `npm run build`. I wasn't sure what to expect from the undefined references but the spinner sizes were correctly updating after changing the value in the `vars.styl` file.
```
> @loadingio/css-spinner@2.0.2 build
> lsc build.ls

Build all CSS-spinners...
   Build Spinners [undefined] undefined 0.0s

Finished.
```
Edit: I think there's still something wrong with the builder. The undefined is resulting in the spinners not building correctly and I don't know how to troubleshoot that. Maybe it's something to do with the color module and changing to ldcolor wasn't actually the fix.

**Comment by zbryikt** [comment]
Hi csphilli, I think this is caused by the notorious incident of marak's color.js module. We did prepared our own colors module `@plotdb/color` earlier this year - yet somehow `css-spinner` was not patched.

So it has been patched along with some dev dependencies upgrades with v2.0.3 released. :)
