### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nradosevic** [loadingio/css-spinner#3]
Hi,
I'm having trouble using your spinners. For example, I downloaded the html code of https://github.com/loadingio/css-spinner/blob/master/build/circle/sample.html, and when I run sample.html in browser I get nothing. Can you please help me?

**Comment by zbryikt** [comment]
Hi chaki90,

it might because that the spinner is default white so it looks like nothing is shown.

here is a working example, with dark background:

https://codepen.io/loadingio/pen/xeJbNp
